apiVersion: v1
kind: Service
metadata:
    name: my-node-port
spec:
    type: NodePort
    ports:
      - port: 3000
        targetPort: 5200
        nodePort: 30002
    selector:
        component: web
    