apiVersion: v1
kind: Pod
metadata:
    name: my-web
    labels:
        component: web-component
spec:
    containers:
        - name: my-web-container
          image: shashankvittal/my-aspnet-core-with-api:k8s
          ports:
            - containerPort: 5200