apiVersion: v1
kind: Service
metadata:
    name: my-node-port
spec:
    type: NodePort
    ports:
      - port: 3000
        targetPort: 5200
        nodePort: 30002
        name: web-port
      - port: 3001
        targetPort: 5400
        nodePort: 30004
        name: app-port
    selector:
        component: web
    