version: "2.0"

services:
    redis-engine:
        image: redis
        restart: always
        ports: 
            - "6379:6379"
    mysql-database:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
    backend-api:
        build:
            context: ./BackendApi
        ports: 
            - "5400:5400"
        environment: 
            REDIS_SERVER: redis-engine
            MYSQL_SERVER: mysql-database
            MYSQL_ROOT_PASSWORD: test
        depends_on:
            - redis-engine
            - mysql-database
        restart: always
    ui:
        build:
            context: ./UI
        ports: 
            - "5200:5200" 
        environment:
            HOSTNAME_API: http://nginx-server/nginx-proxy       
        depends_on:
            - backend-api
        restart: always
    nginx-server:
        build:
            context: ./nginx
        ports: 
            - "8002:80"
        restart: always 
        depends_on: 
            - backend-api
            - ui  
            
    
